import express from "express";
import applyNaukriJobs from "../Controllers/naukriController.js";
import applyInternshalaJobs from "../Controllers/internshalaController.js";
import applyApnaJobs from "../Controllers/apnaJobsController.js";
import checkNaukri from "../Controllers/naukriCheckController.js";
import checkInternshala from "../Controllers/internshalaCheckController.js";
import checkApnaJobs from "../Controllers/apnaJobsCheckController.js";
const applyJobRouter=express.Router();
applyJobRouter.post("/NaukriJobs",applyNaukriJobs);
applyJobRouter.post("/InternshalaJobs",applyInternshalaJobs);
applyJobRouter.post("/ApnaJobs",applyApnaJobs);
applyJobRouter.post("/NaukriCheck",checkNaukri);
applyJobRouter.post("/InternshalaCheck",checkInternshala);
applyJobRouter.post("/ApnaJobsCheck",checkApnaJobs);
export default applyJobRouter;