import express from "express";
import applyNaukriJobs from "../Controllers/naukriController.js";
import applyInternshalaJobs from "../Controllers/internshalaController.js";
import applyApnaJobs from "../Controllers/apnaJobsController.js";
import checkNaukri from "../Controllers/naukriCheckController.js";
import checkInternshala from "../Controllers/internshalaCheckController.js";
import checkApnaJobs from "../Controllers/apnaJobsCheckController.js";
import checkApnaJobsLogin from "../Controllers/apnaJobsLoginController.js";
import checkInternshalaLogin from "../Controllers/internshalaLoginController.js";
import checkNaukriLogin from "../Controllers/naukriLoginController.js";
const applyJobRouter=express.Router();
applyJobRouter.post("/NaukriJobs",applyNaukriJobs);
applyJobRouter.post("/InternshalaJobs",applyInternshalaJobs);
applyJobRouter.post("/ApnaJobs",applyApnaJobs);
applyJobRouter.post("/NaukriCheck",checkNaukri);
applyJobRouter.post("/InternshalaCheck",checkInternshala);
applyJobRouter.post("/ApnaJobsCheck",checkApnaJobs);
applyJobRouter.post("/ApnaJobsLogin",checkApnaJobsLogin);
applyJobRouter.post("/InternshalaLogin",checkInternshalaLogin);
applyJobRouter.post("/NaukriLogin",checkNaukriLogin);
export default applyJobRouter;